// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpyMrmLf4SMgNNgtTID894ZVV9RH1MSeg',
    appId: '1:220516578647:web:1ec09a239284a2be61fa12',
    messagingSenderId: '220516578647',
    projectId: 'kovilhomam',
    authDomain: 'kovilhomam.firebaseapp.com',
    storageBucket: 'kovilhomam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoA40gg0xsno9UaPTy6sE-PlyPFNPqLvA',
    appId: '1:220516578647:android:9a9b65e9ef0d60b861fa12',
    messagingSenderId: '220516578647',
    projectId: 'kovilhomam',
    storageBucket: 'kovilhomam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYu25ON5qSLosMBl4PxlFO89BBQBKNiY',
    appId: '1:220516578647:ios:e6b5551dbd9c3f1a61fa12',
    messagingSenderId: '220516578647',
    projectId: 'kovilhomam',
    storageBucket: 'kovilhomam.appspot.com',
    iosClientId: '220516578647-oppsd67194ci42uk5f9c33ueev36c9js.apps.googleusercontent.com',
    iosBundleId: 'com.avnsm.kovilhomam',
  );
}
